image: node:14.17.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt

test: 
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"

